version: '1'
services:
  schedule:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: schedule-client
    ports:
      - '3003:3003'
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
